# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1e419UPfIA-pcvoYmmBFkAMmv8_mCtk7z
"""

food = "Python's favorite food is perl"

food = 'Python's favorite food is perl'

say = '"Python is very easy." he says.'
print(say)

food = 'Python\'s favorite food is perl'
print(food)

multiline = "Life is \ntoo short \n You need \npython"
print(multiline)

파이썬 기초 공부 :  변수, 숫자, 문자 익히기 실습

multiline=
... Life is too short
... You need python
... 
print(multilin)

multiline = "Life \t is \t too \n short \a 무궁화 \t 꽃이 피었습니다 \t \n You \t need \t python"
print(multiline)

head = "Python"
tail = " is fun!"
aa = head + tail
'Python is fun!'
print(tail)
print(head)
print(aa)

# multistring.py

print("=" * 50)
print("정\t송\t하")
print("=" * 50)